joypad_actionclient:
  ros__parameters:
    actions:
      arm:
        name: "/test_server_node/arm"
        button: 0
      disarm:
        name: "/test_server_node/disarm"
        button: 1
      takeoff:
        name: "/test_server_node/takeoff"
        button: 2
        altitude: 2.0  # Corretto da target_altitude a altitude come da PDF
      landing:
        name: "/test_server_node/landing"
        button: 3
